config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL availab
   root "welcome#index"
 resources :users do
   resources :ideas
 end
   get '/login', as: 'login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  namespace :admin do
   resources :categories
   resources :gifs
   resources :images
   resources :nytimes

end
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_and_belongs_to_many :images, :dependent => :nullify
  has_and_belongs_to_many :gifs, :dependent => :nullify
  has_and_belongs_to_many :nytimes, :dependent => :nullify
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true,
                    uniqueness: true
                    has_many :categories
                    has_many :ideas
  enum role: %w(default admin)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "Invalid Credentials"
      render :new
    end
  end

  def show
    if current_user.id == params[:id].to_i
      @nytimes = Nytime.all
      @gifs = Gif.all
      @images = Image.all
      @user = User.find(params[:id])
      @idea = @user.ideas.new
      @category = Category.all
      @ideas =  Idea.where(:user_id => @user.id)
    else
      render file: "/public/404"
    end
  end

private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/views/users/_form.html.erb
      <%= form_for [@user,@idea] do |f| %>
        <p><%= f.label :title %></p>
        <p><%= f.text_field :title %></p>
        <p><%= f.label :description %></p>
        <p><%= f.text_area  :description %></p>
        <p><%= f.label :category %></p>
        <p><%= f.select :category_id, options_for_select( @category.collect{ |category| ["#{category.name}", category.id] } ), class: 'form-control' %></p>
        <p><%= f.label :image %></p>
        <p><%= f.collection_select :image_ids, @images,:id,:name,{prompt: true}, {:multiple => true } %></p>
        <p><%= f.label :Gif %></p>
        <p><%= f.collection_select :gif_ids, @gifs,:id,:name,{prompt: true}, {:multiple => true } %></p>
        <p><%= f.label :NY_Times_Article %></p>
        <p><%= f.collection_select :nytime_ids, @nytimes,:id,:title,{prompt: true}, {:multiple => true }%></p>
        <p><%= f.submit %></p>
      <% end %>

app/views/users/new.html.erb
<nav>

  <h1>Sign Up</h1>
    <%= link_to "Home", logout_path, class: "logout" %>

</nav>
<div class = "idea-form">
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>
</div>

app/views/users/show.html.erb
<nav>
  <h1>Welcome, <%= current_user.username %>!</h1>
  <%= link_to "Logout", logout_path, class: "logout" %>
</nav>

<div class="user-container">
  <div  class="new-idea-form">
   <h4>New idea?</h4>
    <%= render partial: "form" %>
  </div>
  <div class="idea-container">
    <h4>Your Ideas </h4>
    <% if !@ideas.nil? %>
      <% @ideas.each do |idea| %>
        <div class= "idea-show">
          <div class = "idea-text">
            <p> Idea: <%= idea.title  %></p>
            <p> <%= idea.description  %></p>
            <p>Category: <%= idea.category.name  unless idea.category.nil? %></p>
            <p><%= link_to "Edit", edit_user_idea_path(@user,idea) %></p>
          </div>
          <%idea.images.each do |image| %>
            <div class = "idea-media">
              <p><%= image.name %></p>
              <p> <%=image_tag image.image.url unless image.image.url.nil?%></p>
            </div>
          <% end %>
          <%idea.gifs.each do |gif| %>
            <div class = "idea-media">
              <p><%= gif.name %></p>
              <img src= "<%=gif.url%>">
            </div>
          <% end %>
            <div class = "idea-media">
            <p>  Article:</p>
              <p><%= link_to "#{idea.nytimes.first.title}", user_idea_path(@user, idea)unless  idea.nytimes.empty?  %></p>
            </div>
          <p><%= link_to "Delete Idea", user_idea_path(@user, idea), method: "delete" %></p>
        </div>
       <% end %>
      </div>
    <% end %>
</div>