config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL availab
   root "welcome#index"
 resources :users do
   resources :ideas
 end
   get '/login', as: 'login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  namespace :admin do
   resources :categories
   resources :gifs
   resources :images
   resources :nytimes

end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, optional: true
  has_many :ideas, :dependent => :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @gif = Gif.new
    @gifs = Gif.all
    @image = Image.new
    @images= Image.all
    @category= Category.new
    @categories = Category.all
    @nytime = Nytime.new
    @nytimes = Nytime.all
  end

  def new
    @image = Image.new
    @category= Category.new
  end

  def create
    @category= Category.new(category_params)
      if @category.save!
        redirect_to admin_categories_path
      else
      end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    flash[:success] = "category updated!"
    redirect_to admin_categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:success] = "category deleted!"
    redirect_to admin_categories_path
  end

private
  def category_params
      params.require(:category).permit(:name)
  end

end

app/views/admin/categories/_form.html.erb
<div class = 'forms'>
<%= form_for [:admin, @category]  do |f| %>
<div class="field">
  <p><%= f.label :name %></p>
  <P><%= f.text_field :name %></p>
  <P><%= f.submit %></p>
  </div>
<% end %>
</div>

app/views/admin/categories/_gifs_form.html.erb
<div class = 'forms'>
<%= form_for [:admin, @gif]  do |f| %>
  <div class="field">
    <p><%= f.label :name %></p>
    <P><%= f.text_field :name %></p>
    <P><%= f.submit %></p>
    </div>
  <% end %>
</div>

app/views/admin/categories/_images_form.html.erb
<div class = 'forms'>
<%= form_for [:admin, @image], html: { multipart: true } do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>
      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>  <%= f.label :name %></p>
    <p>  <%= f.text_field :name %></p>
    <p>  <%= f.label :image %><br></p>
    <p>  <%= f.file_field :image %></p>
    <p>  <%= f.submit %></p>
  </div>

<% end %>

</div>

app/views/admin/categories/_ny_form.html.erb
<div class = 'forms'>
<%= form_for [:admin, @nytime]  do |f| %>
  <div class="field">
    <p><%= f.label :title %></p>
    <P><%= f.text_field :title %></p>
    <P><%= f.submit "Find Article" %></p>
    </div>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<nav>
<h1>Update <%= @category.name %> here</h1>
</nav>

<%= form_for [:admin, @category]  do |f| %>
<div class="idea-form">
  <p><%= f.label :name %></p>
  <P><%= f.text_field :name %></p>
  <P><%= f.submit %></p>
  </div>
<% end %>

app/views/admin/categories/index.html.erb
<nav>
  <h1>Welcome to the secret admin place</h1>
  <%= link_to "Logout", root_path, class: "logout" %>
</nav>

  <h5>Make a category </h5>
  <%= render partial: "form" %>
  <h5>Categories ></h5>
  <div class = "cat-contain">
    <div class= "categories-show">
      <%@categories.each do |category|%>
        <div class= "cat-show">
          <p><%=category.name%></p>
          <%= link_to "Edit", edit_admin_category_path(category) %>
          <%= link_to "Delete", admin_category_path(category) , method: "delete" %>
        </div>
      <% end %>
    </div>
  </div>
  <h5>Upload an image </h5>
  <%= render partial: "images_form" %>
  <h5>Images ></h5>
  <div class = "cat-contain">
    <div class = "show-title">
    </div>
    <div class= "categories-show">
      <% @images.each do |image| %>
        <div class= "image-show">
          <P><%= image.name %></P>
          <p><%= image_tag image.image.url unless image.image.url.nil? %></p>
          <p><%=link_to "Delete", admin_image_path(image) , method: "delete" %></p>
        </div >
      <%end%>
    </div>
  </div>
<h5>Upload a gif </h5>
<%= render partial: "gifs_form" %>
<h5>Giphs ></h5>
<div class = "cat-contain">
  <div class= "categories-show">
    <%@gifs.each do |gif| %>
      <div class= "image-show">
        <img src= "<%=gif.url%>">
          <p><%=link_to "Delete", admin_gif_path(gif) , method: "delete" %></p>
      </div>
    <% end %>
  </div>
</div>
  <h5>Find a New York Times Article </h5>
  <%= render partial: "ny_form" %>
  <h5>Articles ></h5>

  <%@nytimes.each  do |article| %>
    <div class = 'image-show'>
      <p> <%= link_to "#{article.title}" , admin_nytime_path(article)%></p>
           <%= link_to "Delete", admin_nytime_path(article) , method: "delete" %>
    </div>
  <% end %>

app/views/admin/categories/new.html.erb
<h3>Make a category here</h3>

<%= render partial: "form" %>